# Generated by Django 2.2 on 2020-07-08 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmat', '0002_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='chellenge',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='topiclist',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
