# Generated by Django 2.2 on 2020-07-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmat', '0003_auto_20200708_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chellenge',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topiclist',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
